### ISSUE TITLE
scripts module failed 

### ISSUE THREAD

**Issue by Tjkent88** [alivx/CIS-Ubuntu-20.04-Ansible#126]
**Describe the bug**
Permission error when trying to run any tasks with the script module

**To Reproduce**
1. Ubuntu 22.04
2. Run playbook 
3. See error

**Expected behavior**
Permissions error when trying to run the scrips

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - python version [e.g. python 3.6.9]
 - ansible version [e.g. 2.9.4]

**Additional context**
adding to the script modules fixes the issue
      args:
        executable: /bin/sh

**Comment by jvleminc** [comment]
Can you add an example/log?

**Comment by jvleminc** [comment]
BTW, this repo is named CIS-Ubuntu-20.04-Ansible, it's probably not ready for 22.04 as is...

**Comment by Tjkent88** [comment]
Yes, I am aware of the repo, however, I couldn't find a repo for 22 and figured this was a good place to start. Is there a repo for 22 and I missed it? Please send that if there is. If there isn't, I have a handful of changes to get this started on Ubuntu 22 and can send in a PR or something if you are interested. Just let me know.

**Comment by jvleminc** [comment]
AFAIK @alivx hasn't started one (yet).
I am going to close this issue, kindly reopen it if it happens in 20.04 as well.
