### ISSUE TITLE
5.4.1.1 - failure on fresh install

### ISSUE THREAD

**Issue by ash-robinson** [alivx/CIS-Ubuntu-20.04-Ansible#23]
**Failure on standard execution during task:** 
5.4.1.1 Ensure password expiration is 365 days or less | chage

stderr: _chage: user 'ubuntu' does not exist in /etc/passed_

**Build:**
 - OS: [Ubuntu 20.04 LTS]
 - python version [Python 3.8.5]
 - ansible version [2.9.6]

**Terminal error message below:**
![image](https://user-images.githubusercontent.com/3867249/104719334-371cb700-5724-11eb-8747-6201981d3966.png)

**Comment by alivx** [comment]
@ash-robinson, Before running the playbook, you need to check the config under `https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/blob/master/defaults/main.yml`, and make sure to change users, subnets,,,etc.

For your case, you can find config under `defaults/main.yml`:
```
## 5.4.1.1 Ensure password expiration is 365 days or less
list_of_os_users:
  - ubuntu
```

**Comment by ash-robinson** [comment]
That's great to know, thanks.

Quick question on that, I am using ansible-galaxy to install this repo as part of a standard build script, is there a way you know of to override the defaults/main.yml within that context?

**Comment by alivx** [comment]
Yes,
Read this 

- https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html

Check the last section of that URL.

**Comment by ash-robinson** [comment]
Perfect, thanks for your help
