### ISSUE TITLE
Fix Python 2 Deprecation warnings in Travis CI build.

### ISSUE THREAD

**Issue by estenrye** [alivx/CIS-Ubuntu-20.04-Ansible#25]
**Describe the bug**
Small change to Travis CI build file to use Python 3 in anticipation of pip 21.0 deprecating support for Python 2 in January 2021.

**To Reproduce**
Trigger a build in Travis CI

**Expected behavior**
Deprecation warning should not be visible.

**Comment by alivx** [comment]
That changed merged 😎
