### ISSUE TITLE
Travis CI Build fails to publish to ansible galaxy

### ISSUE THREAD

**Issue by estenrye** [alivx/CIS-Ubuntu-20.04-Ansible#30]
**Describe the bug**
The Travis CI build uses the name of the repository to define the name of the role to upload.
The repository name contains characters that are not valid for an ansible role name.

**To Reproduce**
1. Fork the repository.
2. attempt to configure a Travis CI build.

**Expected behavior**
Forking the repository should result in a new repo with a working Travis CI build.

**Workaround**
Renaming the forked repository addresses naming incompatibility but results in failing tests as test.yml is hard coded to the repository name.

**Comment by alivx** [comment]
That wired, 
Check the this Travis build
https://travis-ci.com/github/alivx/CIS-Ubuntu-20.04-Ansible

Can you please give me more debug log or details

**Comment by alivx** [comment]
is there any update
