### ISSUE TITLE
inventory_dir not defined, seemingly only on re-run.

### ISSUE THREAD

**Issue by brendan-s1** [alivx/CIS-Ubuntu-20.04-Ansible#37]
**Describe the bug**
Re-ran this against an ubuntu 20.04 instance in AWS and got:  

atal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'inventory_dir' is undefined\n\nThe error appears to be in '/tmp/CIS-Ubuntu-20.04-Ansible/tasks/section_1_Initial_Setup.yaml': line 873, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# has to be defined in the variable \"custom_motd_file_path\".\n- name: 1.8.1.1 Ensure message of the day is configured properly\n  ^ here\n"}

**To Reproduce**
1. Run playbook with all tasks.
2. Make some changes in mail.yaml. 
3. Re-Run playbook, got error.

**Expected behavior**
Expected it to complete without error.

**Screenshots**

**Desktop (please complete the following information):**
Ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]

**Additional context**
None.

**Comment by alivx** [comment]
Did you set your playbook as below structure:

$ ls
```
run.yaml 
CIS-Ubuntu-20.04-Ansible
host
```

`run.yaml` is your playbook.
`CIS-Ubuntu-20.04-Ansible` clone of this repo.
`host` is your host file(inventory)

**Comment by alivx** [comment]
Is there any update
