### ISSUE TITLE
Issue en #5.2.14: superfluous space in sshd algorithms 

### ISSUE THREAD

**Issue by jvleminc** [alivx/CIS-Ubuntu-20.04-Ansible#4]
In test 5.2.14: 
Superfluous space in list of `sshd` algorithms in `/etc/ssh/sshd_config` breaks `sshd`: "diffie-hellman- group14-sha256"
```
    line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman- group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"

```

**Comment by jvleminc** [comment]
I will create a PR for this. After a server restart we lost sshd access. :-/

**Comment by alivx** [comment]
> I will create a PR for this. After a server restart we lost sshd access. :-/

You are awsome, Thank you 👍🏻
