### ISSUE TITLE
missing var allowd_hosts in 5.1.8

### ISSUE THREAD

**Issue by liuyangc3** [alivx/CIS-Ubuntu-20.04-Ansible#42]
**Describe the bug**

`allowd_hosts: "ALL: 0.0.0.0/0.0.0.0, 192.168.2.0/255.255.255.0"` in defaults/main.yaml not used in any task

**Comment by alivx** [comment]
Yes, it should be in use.
I will check and push that part

**Comment by alivx** [comment]
There is no update, closing..
