### ISSUE TITLE
Update about section to 20.04

### ISSUE THREAD

**Issue by EricHeath-AI** [alivx/CIS-Ubuntu-20.04-Ansible#50]
**Describe the bug**
Easy one: about section lists 18.04 while the rest of the project has updated to 20.04.

**To Reproduce**
1. Go to https://github.com/alivx/CIS-Ubuntu-20.04-Ansible
2. Top right "about" text.
3. ![Screen Shot 2021-05-14 at 12 30 14 PM](https://user-images.githubusercontent.com/9936027/118319921-49c7b280-b4b0-11eb-8a13-44fc878c3997.png)

**Expected behavior**
Update text to 20.04.

**Screenshots**
![Screen Shot 2021-05-14 at 12 30 14 PM](https://user-images.githubusercontent.com/9936027/118319921-49c7b280-b4b0-11eb-8a13-44fc878c3997.png)

**Desktop (please complete the following information):**
- all / web browser.

**Additional context**
n/a

**Comment by alivx** [comment]
Done, I added that part :)
