### ISSUE TITLE
Missing DIY tag in #1.2.1 Ensure package manager repositories are configured

### ISSUE THREAD

**Issue by bvdbasch** [alivx/CIS-Ubuntu-20.04-Ansible#51]
Hi,

I was checking out this repo and noticed that the `- diy` tag appears to be missing under section 1.2.1 (whilst the description you've typed clearly states that  `the specifics on patch update procedures are left to the organization.`

Take a look here: https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/blob/e1027faebf58a6473eb1d8632107f31c23f7e575/tasks/section_1_Initial_Setup.yaml#L455

Just thought you wanted to know. 

Thanks for the playbook and I hope you have a great day.

**Comment by alivx** [comment]
Hello,
Thank you.

I added the tag 'DIY" because that step needs a manual action, not an automated way.
I guess it will be better to rename it to `manual` instead of `diy`

**Comment by bvdbasch** [comment]
Sorry to bump the already closed issue, but I think you may have possibly misunderstood. What I meant to convey is that the tags under [line 455](https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/blob/e1027faebf58a6473eb1d8632107f31c23f7e575/tasks/section_1_Initial_Setup.yaml#L455) are not complete. There should be a `DIY` tag since this is not handled by automation.

~Bonno
