### ISSUE TITLE
Missing curly braces for variable grub_backlog_limit in section 4.1.1.4

### ISSUE THREAD

**Issue by gavinlee12** [alivx/CIS-Ubuntu-20.04-Ansible#53]
Hi Alivx,

Hope you are having a wonderful day!

https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/blob/1e861532692b454cbbf145b968b072eb603d70a3/tasks/section_4_Logging_and_Auditing.yaml#L47

I believe this should be referencing the variable grub_backlog_limit and will need the curly braces.

**Comment by alivx** [comment]
Thank you,
I solved this case :)
