### ISSUE TITLE
 SSH MaxStartups and  MaxSessions could be parameterized

### ISSUE THREAD

**Issue by jvleminc** [alivx/CIS-Ubuntu-20.04-Ansible#6]
Instead of hardcoding the value in the playbook file (tests 5.2.21 and 5.2.22), it'd be better to allow the value to be configured in the main.yml file, fore easy customisation.

I will create a PR for this.

**Comment by alivx** [comment]
Yes, it's better to use a configuration file instead of using a hardcode in the playbook.
Thank you for your amazing contribution @jvleminc :)

**Comment by alivx** [comment]
Change merged 
https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/pull/7
