### ISSUE TITLE
Logrotate package

### ISSUE THREAD

**Issue by mxm-tr** [alivx/CIS-Ubuntu-20.04-Ansible#63]
**Describe the bug**
An error message appears when checking 4.4

**To Reproduce**
1. Clone the repository in a subdirectory and create a playbook containing the role CIS-Ubuntu-20.04-Ansible.
2. Run playbook with tag level_1_server
3. See error

**Expected behavior**
The install expects logrotate to be present, is that expected?
If so, should the package be installed by the role?

**Screenshots**

```
TASK [CIS-Ubuntu-20.04-Ansible : 4.4 Ensure logrotate assigns appropriate permissions] ****************************************************************************************************************************
fatal: [185.52.192.201]: FAILED! => {"changed": false, "msg": "Destination /etc/logrotate.conf does not exist !", "rc": 257}

RUNNING HANDLER [CIS-Ubuntu-20.04-Ansible : journald restart] *****************************************************************************************************************************************************

RUNNING HANDLER [CIS-Ubuntu-20.04-Ansible : rsyslog restart] ******************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
185.52.192.201             : ok=153  changed=74   unreachable=0    failed=1    skipped=29   rescued=0    ignored=3   

```

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - python version: python 3.8.8
 - ansible version: core 2.11.6

Additional info:

Adding the package installation passed this step successfully

**Comment by alivx** [comment]
logrotate installed by default in the ubuntu,
Make sure to install it via the below command
sudo apt-get install logrotate -y

**Comment by alivx** [comment]
There is no update, closing..
