### ISSUE TITLE
Default template referenced in section_1_Initial_Setup.yaml is "isssue" instead of issue, typo causing failure.

### ISSUE THREAD

**Issue by joseph-cagt** [alivx/CIS-Ubuntu-20.04-Ansible#92]
**Describe the bug**
In section_1_Initial_Setup.yaml:

Line 1021: 
- "files/templates/isssue.j2"

Line 1050:
- "files/templates/isssue.net.j2"

**To Reproduce**
1. Run playbook 
2. See error

**Expected behavior**
No Error

**Screenshots**
![image](https://user-images.githubusercontent.com/104380712/169291794-ed9f0dbf-4fa3-434b-8e80-a38d3cbb8d0f.png)

**Comment by alivx** [comment]
Fixed https://github.com/alivx/CIS-Ubuntu-20.04-Ansible/pull/94
